[package]
name = "gw-backend"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gw-backend"
path = "src/main.rs"

[dependencies]
log = "0.4.29"
simplelog = "0.12"
helpers = { path = "../helpers" }
managers = { path = "../managers" }
rouille = "3.6"
rusqlite = "0.38"
open = "5"
